import type { Metadata } from "next";
import { Suspense } from "react";
import { Providers } from "../providers";
import HeaderMain from "@/components/header/header-main";
import Footer from "@/components/footer/footer-products";
import SpeedInsights from "@/components/SpeedInsightsDynamic";
import TelegramChatWidget from "@/components/products/telegram-chat/TelegramChatWidgetDynamic";

import "@/styles/globals.css";
import { ThemeContextProvider } from "@/context/themeContext";

export const metadata: Metadata = {
  title: "Funny Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <ThemeContextProvider>
        <Providers>
          <div id="header">
            <HeaderMain />
          </div>
          <div id="overlay-header"></div>
          <div id="page">
            {children}
            <Suspense fallback={null}>
              <TelegramChatWidget />
            </Suspense>
            <div id="reviews"></div>
          </div>
          <div id="dialog-overlay"></div>
        </Providers>
      </ThemeContextProvider>
      <Footer />
      <Suspense fallback={null}>
        <SpeedInsights />
      </Suspense>
    </section>
  );
}
