import type { Metadata } from "next";
import { Suspense } from "react";
import { Providers } from "../providers";
import HeaderMain from "@/components/header/header-main";
import Footer from "@/components/footer/footer-products";
import PageThemeContainer from "@/components/layout/page-theme-container";
import SpeedInsights from "@/components/SpeedInsightsDynamic";
import TelegramChatWidget from "@/components/products/telegram-chat/TelegramChatWidgetDynamic";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Funny Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Providers>
        <div id="header">
          <HeaderMain />
        </div>
        <div id="overlay-header"></div>
        <PageThemeContainer>
          {children}
          <Suspense fallback={null}>
            <TelegramChatWidget />
          </Suspense>
          <div id="reviews"></div>
        </PageThemeContainer>
        <div id="dialog-overlay"></div>
        <Footer />
      </Providers>
      <Suspense fallback={null}>
        <SpeedInsights />
      </Suspense>
    </section>
  );
}
