import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Providers } from "../providers";
import HeaderMain from "@/components/header/header-main";
import Footer from "@/components/footer/footer-products";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Funny Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Providers>
          <div id="header">
            <HeaderMain />
          </div>
          <div id="overlay-header"></div>
          <div id="page">{children}</div>
          <div id="dialog-overlay"></div>
        </Providers>
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
